### ISSUE TITLE
This hook is global for app.

### ISSUE THREAD

**Issue by peerless2012** [keith2018/TLSHook#1]
Run this demo, and we can see, that the SurfaceView is clear to Blue, even if the window backgroud is clear to Blue.

**Comment by keith2018** [comment]
> Run this demo, and we can see, that the SurfaceView is clear to Blue, even if the window backgroud is clear to Blue.

Yes, it will hook the whole process's GL function call.
if you want to hook the SurfaceView only, try check the egl context before hook

```
void hook_glClearColor(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha) {
  EGLContext ctx = eglGetCurrentContext();
  if (ctx ...) {  // check context
	  LOGD("hook call glClear: (%f, %f, %f, %f)", red, green, blue, alpha);
	  if (cb_glClearColor) {
		cb_glClearColor(0.f, 0.f, 1.f, 1.f);
	  }
  }
}
```

**Comment by peerless2012** [comment]
Yes! it works, and i create a #2 to impl this feature, please check it.

**Comment by keith2018** [comment]
> Yes! it works, and i create a #2 to impl this feature, please check it.

thx for your contribution !
